version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: 
  
  acme-companion:
    image: nginxproxy/acme-companion
    depends_on: 
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      DEFAULT_EMAI: acme@acme.com

  azure-openai:
    image: ghcr.io/wenxcs/azure-openai-proxy
    depends_on: 
      - acme-companion
    expose:
      - "8080"
    environment:
      AZURE_OPENAI_ENDPOINT: "https://${ENDPOINT}/"
      VIRTUAL_HOST: "${HOST}"
      LETSENCRYPT_HOST: "${HOST}"
      LETSENCRYPT_EMAIL: acme@acme.com
      VIRTUAL_PORT: "8080"

volumes:
  acme: {}
  certs: {}
  vhost: {}
  html: {}